# arguments
task_name: countdown  # binary-addition
param_type: bert # mlp, transformer, bert, gpt
is_ebm: False
# max_len: 128
# special_tokens: ['<mask>']
load_ebm_ckpts: False ###########
continue_train: False #######for further training with fully masked t2 (inference) after trained on mlm
device: cuda #cpu, cuda


# 这个参数暂时无用
models:
  llama3.1-8b-instruct:
    # regular tokens: [0-127999]
    # special indices: [128000, 128009]
    # special_tokens_map: {'bos_token': '<|begin_of_text|>', 'eos_token': '<|eot_id|>'}
    name: meta-llama/Llama-3.1-8B-Instruct
  bert:
    d_model: 384 #128 # 32
    n_layers: 3 #6
    heads: 12 #8

  gpt: #from scratch
    # d_model: #?
    max_len: 50 #512
    d_model: 384 #The same as "n_embd" in config.json
    n_layers: 3
    heads: 12
    vocab_size: 31

#all tasks
tasks:
  binary-addition:
    name: binary-addition
    inp_len: 18
    out_len: 9 #k
    num_classes: 3 #MASK token + vocabulary(size=2)  #vocab_size = binary + 4 special tokens for BERT
    train_size: 1800
    val_size: 200
    metrics: ['acc']

  binary-inversion:
    name: binary-inversion
    inp_len: 12
    out_len: 10 #k
    num_classes: 2 #d #binary (exclude special tokens, eg. <mask>)
    train_size: 1800
    val_size: 200
    metrics: ['acc']

  binary-subtraction:
    name: binary-subtraction
    inp_len: 12
    out_len: 10 #k
    num_classes: 2 #d #binary (exclude special tokens, eg. <mask>)
    train_size: 1800
    val_size: 200
    metrics: ['acc']

  countdown:
    name: countdown
    metrics: ['acc']
    num_classes: 31 #?
    max_len: 50

  sudoku:
    name: sudoku
  #   inp_len: ? #<9x9?
  #   out_len: ?
    num_classes: 9 #1~9
  #   train_size: ?
  #   val_size: ?


train:
  stage: inference #pretrain (mm_energy), sft (), inference
  epochs: 1 #1 #40 #same as diffusion-vs-ar ########
  lr: 1e-4 #3e-4 #有用: init optimizer
  early_stop_threshold: 0.01 #没用?
  contrast: True
  batch_size:  200 #200 #100 #sudoku must be 1
  visualize: True
  wandb: True ####################### 

sampling:
  stage: inference #sft(default mask rate is t),inference(fully mask, depend on sampler)
  batch_size: 1 #4
  times: 4
  steps: 1
  sampler: gibbs #argmin_energy(traditional loss), gibbs(ebm method)
  wandb: False
  # temperature: 1.0cd

visualize:
  batch_step: 10 #visualize per <batch_step> number of batches
  time_step: 2 #the time step between consecutive screenshots 