# arguments
task_name: cd3 # countdown
param_type: fast # mlp, transformer, bert, gpt, fast
model_arc: gpt #bert
model_scale: tiny #tiny: 6M, 
is_ebm: False
max_k: 10 
# max_len: 128
# special_tokens: ['<mask>']
load_ebm_ckpts: True ###########
continue_train: False #######for further training with fully masked t2 (inference) after trained on mlm
cont_epoch: 0
parallel: False ########currently only supports training with parallel_train.py
device: cuda #cpu, cuda
visualize: False ###########
project_root: /home/yichuan/HKU/EBM/ire_reasoning


# 这个参数暂时无用 (全部看config json file, 不管是不是build-from-scratch)
models:
  bert:
    d_model: 384 #128 # 32
    n_layers: 3 #6
    heads: 12 #8

  gpt: #from scratch (no use now, Sep10th)
    # d_model: #?
    max_len: 50 #512
    d_model: 384 #The same as "n_embd" in config.json
    n_layers: 3
    heads: 12
    vocab_size: 31

#all tasks
tasks:
  cd3:
    name: cd3 #TODO: 4,5
    metrics: ['acc']
    num_classes: 31 #?
    max_len: 50
    warmup_steps: 10000

  cd4:
    name: cd4
    metrics: ['acc']
    num_classes: 31
    max_len: 55
    warmup_steps: 10000

  cd5: 
    name: cd5
    metrics: ['acc']
    num_classes: 31
    max_len: 75
    warmup_steps: 10000

  sudoku:
    name: sudoku
    metrics: ['acc']
    num_classes: 14 #1~9 + 5 special_toks
    max_len: 92 #9x9 + 9 padding positions for batchalized unmasking schedule
    warmup_steps: 10000



train:
  stage: inference #pretrain (mm_energy), sft (), inference
  epochs: 600 #600 #same as diffusion-vs-ar ########
  lr: 1e-3 #3e-4  #有用: init optimizer
  early_stop_threshold: 0.01 #没用?
  contrast: False ##############
  batch_size:  1 #14 #16 #200 #100 #sudoku must be 1 #pseudolikelihood_batched: at most 16
  visualize: True
  local_log: True ####################### 

sampling:
  stage: inference #sft(default mask rate is t),inference(fully mask, depend on sampler)
  epochs: 1
  batch_size: 32 #32
  times: 4 #4: 93.7
  # steps: 1 #?
  sampler: gibbs #argmin_energy(traditional loss), gibbs(ebm method)
  local_log: False
  # temperature: 1.0cd

# visualize:
#   batch_step: 10 #visualize per <batch_step> number of batches
#   time_step: 2 #the time step between consecutive screenshots 